//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrder()
        {
            this.CustomerOrder_ProductStyle = new HashSet<CustomerOrder_ProductStyle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public Nullable<int> ShippingFee { get; set; }
        public Nullable<int> ReturnedFee { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public System.Guid ShippingId { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder_ProductStyle> CustomerOrder_ProductStyle { get; set; }
        public virtual Shipping_District Shipping_District { get; set; }
    }
}
