//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder_ProductStyle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrder_ProductStyle()
        {
            this.ProductCode_Out = new HashSet<ProductCode_Out>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CustomerOrderId { get; set; }
        public System.Guid ProductStyleId { get; set; }
        public Nullable<int> CurrentPrice { get; set; }
        public Nullable<int> SaleOffPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual ProductStyle ProductStyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCode_Out> ProductCode_Out { get; set; }
    }
}
