//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_ProductIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_ProductIn()
        {
            this.ProductCode_In = new HashSet<ProductCode_In>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime ImportDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> SupplierOrderId { get; set; }
    
        public virtual SupplierOrder SupplierOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCode_In> ProductCode_In { get; set; }
    }
}
