//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_District
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipping_District()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DistrictId { get; set; }
        public Nullable<System.Guid> ShippingId { get; set; }
        public Nullable<int> ShippingFee { get; set; }
        public Nullable<int> ReturnedFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        public virtual District District { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
