//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrder()
        {
            this.Inventory_ProductIn = new HashSet<Inventory_ProductIn>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Product_Supplier_Id { get; set; }
        public Nullable<System.Guid> InventoryId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_ProductIn> Inventory_ProductIn { get; set; }
        public virtual Supplier_Product Supplier_Product { get; set; }
    }
}
